# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhairdressings', '0003_auto_20160417_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhairdressing',
            name='description',
            field=models.TextField(help_text=b'Describe la informacion necesaria de la peluqueria'),
        ),
        migrations.AlterField(
            model_name='adminhairdressing',
            name='zipcode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='speciality',
            field=models.TextField(help_text=b'Redacta las especialidades del peluquero', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Lunes'), (2, b'Martes'), (3, b'Miercoles'), (4, b'Jueves'), (5, b'Viernes'), (6, b'Sabado')], default=1, verbose_name=b'Dia'),
        ),
    ]
